version: "3.8"

services:
  web:
    build: ./frontend
    ports:
      - 3002:3000
    volumes:
      - ./frontend:/app
  web-tests:
    image: docker-web
    volumes:
      - ./frontend:/app
    command: npm test
  api:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/vidly
    volumes:
      - ./backend:/app
    depends_on: 
      - db
    command: ./docker-entrypoint.sh
  db:
    image: mongo:4.0-xenial
    ports:
      - 27018:27017
    volumes:
      - vidly:/data/db

volumes:
  vidly:
